/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import Control.ProductosControlBD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author astuard
 */
public class EditarProducto extends javax.swing.JFrame {
    
    
    ProductosControlBD productos = new ProductosControlBD ();
    
    private int idProducto;

    /**
     * Creates new form Principal
     */
    public EditarProducto(int idProducto, String NombreProducto, float precio, int cantidad, String categoria) {
        initComponents();       

        this.idProducto = idProducto;
        textNombre.setText(NombreProducto);
        textPrecio.setText(String.valueOf(precio));
        textCantidad.setText(String.valueOf(cantidad));

        // Validar solo números enteros en textCantidad
        textCantidad.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) { 
                    e.consume(); // Bloquea la entrada
                }
            }
        });

    // Validar solo números y punto decimal en textPrecio
    textPrecio.addKeyListener(new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            if (!Character.isDigit(c) && c != '.') {
                e.consume(); // Bloquea la entrada
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textCantidad = new javax.swing.JTextField();
        textCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAceptarModificacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MODIFICAR DATOS DE LOS PRODUCTOS");
        jLabel1.setMaximumSize(new java.awt.Dimension(780, 380));
        jLabel1.setMinimumSize(new java.awt.Dimension(780, 380));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        textPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, 40));
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, 40));
        jPanel1.add(textCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 210, 40));
        jPanel1.add(textCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 250, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombre de producto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Precio del producto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        botonAceptarModificacion.setBackground(new java.awt.Color(204, 204, 204));
        botonAceptarModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAceptarModificacionMousePressed(evt);
            }
        });
        botonAceptarModificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Aceptar ");
        botonAceptarModificacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(botonAceptarModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 110, 40));

        jButton1.setText("Regresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarModificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarModificacionMousePressed
        // BOTON ACEPTAR MODIFICACIONES
        String NombreProducto = textNombre.getText();
        String precioStr = textPrecio.getText();
        String cantidadStr = textCantidad.getText();
        String categoria = textCategoria.getText();

        if (NombreProducto.equals("") || precioStr.equals("") || cantidadStr.equals("") || categoria.equals("")) {
            JOptionPane.showMessageDialog(null, "¡Ingrese datos para modificar!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Convertir a float e int
                float precio = Float.parseFloat(precioStr);
                int cantidad = Integer.parseInt(cantidadStr);

                // Llamar a la función modificar con valores correctos
                productos.modificar(idProducto, NombreProducto, precio, cantidad, categoria);
                JOptionPane.showMessageDialog(null, "Producto Modificado con éxito", "Modificado", JOptionPane.INFORMATION_MESSAGE);

                // Recargar la ventana
                GestionProductos ventana = new GestionProductos();
                ventana.setSize(780, 380);
                ventana.setLocation(0,0);
                jPanel1.removeAll();
                jPanel1.add(ventana, BorderLayout.CENTER);
                jPanel1.revalidate();
                jPanel1.repaint();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "¡Ingrese un precio y una cantidad válidos!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonAceptarModificacionMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Interfas vtn=new Interfas();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAceptarModificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
