/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import Control.ProductosControlBD;
import Modelo.Productos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.Comparator;


/**
 *
 * @author astuard
 */
public class GestionProductos extends javax.swing.JFrame {
    
    ProductosControlBD productos = new ProductosControlBD();

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
        llenarTabla();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        textProducto = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRecargar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(820, 450));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(780, 380));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Cantidad", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        textProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        botonEliminar.setBackground(new java.awt.Color(204, 0, 0));
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEliminarMousePressed(evt);
            }
        });
        botonEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar");
        botonEliminar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 100, -1));

        botonModificar.setBackground(new java.awt.Color(236, 236, 130));
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonModificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonModificarMousePressed(evt);
            }
        });
        botonModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modificar");
        botonModificar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 100, -1));

        botonAgregar.setBackground(new java.awt.Color(105, 238, 105));
        botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAgregarMousePressed(evt);
            }
        });
        botonAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar Producto");
        botonAgregar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 170, -1));

        botonBuscar.setBackground(new java.awt.Color(18, 90, 173));
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonBuscarMousePressed(evt);
            }
        });
        botonBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        botonBuscar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Buscar por nombre del producto:");

        botonRecargar.setBackground(new java.awt.Color(0, 204, 204));
        botonRecargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRecargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRecargarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRecargarMousePressed(evt);
            }
        });
        botonRecargar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" 🔄");
        botonRecargar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(textProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(botonRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(4, 4, 4)
                            .addComponent(textProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 380));

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(815, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 53, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 397, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseEntered
        // BOTON ELIMINAR ESTUDIANTE
        botonEliminar.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_botonEliminarMouseEntered

    private void botonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseExited
        // BOTON ELIMINAR ESTUDIANTE
        botonEliminar.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_botonEliminarMouseExited

    private void botonEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMousePressed
        // BOTON ELIMINAR ESTUDIANTE
        eliminarFila();
    }//GEN-LAST:event_botonEliminarMousePressed

    private void botonModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseEntered
        // BOTON MODIFICAR ESTUDIANTE
        botonModificar.setBackground(new Color(153,153,0));
    }//GEN-LAST:event_botonModificarMouseEntered

    private void botonModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseExited
        // BOTON MODIFICAR ESTUDIANTE
        botonModificar.setBackground(new Color(204,204,0));
    }//GEN-LAST:event_botonModificarMouseExited

    private void botonModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMousePressed
        // BOTON MODIFICAR ESTUDIANTE
        modificarFila();
    }//GEN-LAST:event_botonModificarMousePressed

    private void botonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseEntered
        // BOTON AGREGAR NUEVO ESTUDIANTE
        botonAgregar.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_botonAgregarMouseEntered

    private void botonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseExited
        // BOTON AGREGAR NUEVO ESTUDIANTE
        botonAgregar.setBackground(new Color(0,204,0));
    }//GEN-LAST:event_botonAgregarMouseExited

    private void botonAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMousePressed
        // BOTON AGREGAR NUEVO ESTUDIANTE
        AgregarPoducto vtnp=new AgregarPoducto();
        vtnp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAgregarMousePressed

    private void botonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseEntered
        // BOTON BUSCARESTUDIANTE
        botonBuscar.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_botonBuscarMouseEntered

    private void botonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseExited
        // BOTON BUSCAR ESTUDIANTE
        botonBuscar.setBackground(new Color(18,90,173));
    }//GEN-LAST:event_botonBuscarMouseExited

    private void botonBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMousePressed
        // BOTON BUSCAR  ESTUDIANTE
        String NombreProducto = textProducto.getText();
            
        boolean encontrado = false;
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        List<Productos> productosLista = productos.listado();
        for (Productos producto : productosLista) {
            if (NombreProducto.equals(producto.getNombreProducto())) {
                encontrado = true;
                Object[] fila = {
                    producto.getIdProducto(),
                    producto.getNombreProducto(),
                    producto.getPrecio(),  
                    producto.getCantidad(),    
                    producto.getCategoria(),   
                    
                };
                modelo.addRow(fila);
            }

            // Asignar el modelo al JTable
            jTable2.setModel(modelo);
        }
        
        if (encontrado == false) {
            JOptionPane.showMessageDialog(null, "No se encontro ningun estudiante con esa cédula", "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
        }
      
     

    }//GEN-LAST:event_botonBuscarMousePressed

    private void botonRecargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecargarMouseEntered
        // BOTON RECARGAR TABLA
        botonRecargar.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_botonRecargarMouseEntered

    private void botonRecargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecargarMouseExited
        // BOTON RECARGAR TABLA
        botonRecargar.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_botonRecargarMouseExited

    private void botonRecargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecargarMousePressed
        // BOTON RECARGAR TABLA
        llenarTabla();
    }//GEN-LAST:event_botonRecargarMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Interfas vtn=new Interfas();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        List<Productos> productosLista = ProductosControlBD.listado();
        for (Productos producto : productosLista) {
            Object[] fila = {
                producto.getIdProducto(),
                producto.getNombreProducto(),
                producto.getPrecio(),  
                producto.getCantidad(),    
                producto.getCategoria(),   
                   
            };
            modelo.addRow(fila);
        }

        // Asignar el modelo al JTable
        jTable2.setModel(modelo);    
    }
    

    private void eliminarFila() {
        int selectedRow = jTable2.getSelectedRow(); 
        if (selectedRow != -1) { 
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas Eliminar la fila seleccionada?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                int idProductos = (int) jTable2.getValueAt(selectedRow, 0);
                productos.eliminar(idProductos);
                llenarTabla();
            } 

        } else {
            JOptionPane.showMessageDialog(null, "¡Seleccione la fila que desea eliminar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void modificarFila() {
        int selectedRow = jTable2.getSelectedRow(); 
        if (selectedRow != -1) { 
            int idProducto = (int) jTable2.getValueAt(selectedRow, 0);
            String NombreProducto= (String) jTable2.getValueAt(selectedRow, 1);
            float precio = Float.parseFloat(jTable2.getValueAt(selectedRow, 2).toString()); 
            int cantidad = Integer.parseInt(jTable2.getValueAt(selectedRow, 3).toString()); 
            String categoria = (String) jTable2.getValueAt(selectedRow, 4);

            EditarProducto ventanaModificar = new EditarProducto(idProducto, NombreProducto, precio,  cantidad , categoria);
   

        } else {
            JOptionPane.showMessageDialog(null, "¡Seleccione la fila que desea modificar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAgregar;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JPanel botonEliminar;
    private javax.swing.JPanel botonModificar;
    private javax.swing.JPanel botonRecargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField textProducto;
    // End of variables declaration//GEN-END:variables
}
