/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author astuard
 */
public class Login extends javax.swing.JFrame {
    int xMause,yMause;
    String username;
    String password ;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JPasswordField();
        lbUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        verde = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        panelx = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btLogin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(840, 320));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lbContraseña.setText("********");
        lbContraseña.setBorder(null);
        lbContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbContraseñaMousePressed(evt);
            }
        });
        lbContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, -1));

        lbUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lbUsuario.setText("Ingrese su usuario o correo electronico");
        lbUsuario.setBorder(null);
        lbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbUsuarioMousePressed(evt);
            }
        });
        lbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 126, -1, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 220, 15));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Organiza tu inventario!!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(69, 123, 157));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 290));

        verde.setBackground(new java.awt.Color(30, 54, 88));
        verde.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                verdeMouseDragged(evt);
            }
        });
        verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout verdeLayout = new javax.swing.GroupLayout(verde);
        verde.setLayout(verdeLayout);
        verdeLayout.setHorizontalGroup(
            verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        verdeLayout.setVerticalGroup(
            verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        btLogin.setBackground(new java.awt.Color(204, 204, 204));
        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin.setText("Ingresar");
        btLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLoginMouseExited(evt);
            }
        });
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, 30));

        panelx.setBackground(new java.awt.Color(204, 204, 204));
        panelx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        X.setBackground(new java.awt.Color(204, 204, 204));
        X.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        X.setText("    x");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });
        panelx.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel1.add(panelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/candado.png.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 20, 30));

        btLogin1.setBackground(new java.awt.Color(204, 204, 204));
        btLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin1.setText("Registrarte");
        btLogin1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLogin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLogin1MouseExited(evt);
            }
        });
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbUsuarioActionPerformed

    private void verdeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeMousePressed
        // TODO add your handling code here:
        xMause=evt.getX();
        yMause=evt.getY();
    }//GEN-LAST:event_verdeMousePressed

    private void verdeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMause,y-yMause);
    }//GEN-LAST:event_verdeMouseDragged

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        // TODO add your handling code here:
        panelx.setBackground(Color.red);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        // TODO add your handling code here:
        panelx.setBackground(Color.gray);
    }//GEN-LAST:event_XMouseExited

    private void btLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseEntered
        // TODO add your handling code here:
        btLogin.setBackground(new Color(29,85,219));
    }//GEN-LAST:event_btLoginMouseEntered

    private void btLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseExited
        // TODO add your handling code here:
        btLogin.setBackground(Color.gray);
    }//GEN-LAST:event_btLoginMouseExited

    private void lbUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuarioMousePressed
        // TODO add your handling code here:
        if(lbUsuario.getText().equals("Ingrese su usuario o correo electronico")){
            lbUsuario.setText("");
            lbUsuario.setForeground(Color.black);
        }
        if(String.valueOf(lbContraseña.getPassword()).isEmpty()){
            lbContraseña.setText("********");
            lbContraseña.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_lbUsuarioMousePressed

    private void lbContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbContraseñaMousePressed
        // TODO add your handling code here:
        if (String.valueOf(lbContraseña.getPassword()).equals("********")){
            lbContraseña.setText("");
            lbContraseña.setForeground(Color.black);
        }
        if (lbUsuario.getText().isEmpty()){
            lbUsuario.setText("Ingrese su usuario o correo electronico");
            lbUsuario.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_lbContraseñaMousePressed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        String username = lbUsuario.getText(); // Asumiendo lbUsuario es JTextField
        String password = new String(lbContraseña.getPassword()); // Asumiendo lbContraseña es JPasswordField

        if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

        String url = "jdbc:postgresql://localhost:5432/Inventrio";
        String usuarioBD = "postgres";
        String contrasenaBD = "messi";

            try (Connection conn = DriverManager.getConnection(url, usuarioBD, contrasenaBD)) {
                String query = "SELECT * FROM usuarios WHERE nombre_usuario = ? AND contrasena = ?";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, username);
                stmt.setString(2, password);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Usuario: " + username + ", Contraseña: " + password);
            
                // Abrir ventana de usuarios después del login
                Interfas vtn=new Interfas();
                vtn.setVisible(true);
                this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
 
    }//GEN-LAST:event_btLoginActionPerformed

    private void lbContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbContraseñaActionPerformed

    private void btLogin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogin1MouseEntered
        // TODO add your handling code here:
        btLogin1.setBackground(new Color(29,85,219));
    }//GEN-LAST:event_btLogin1MouseEntered

    private void btLogin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogin1MouseExited
        // TODO add your handling code here:
        btLogin1.setBackground(Color.gray);
    }//GEN-LAST:event_btLogin1MouseExited

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        // TODO add your handling code here                             

        Usurios vtnu  =new Usurios();
        vtnu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField lbContraseña;
    private javax.swing.JTextField lbUsuario;
    private javax.swing.JPanel panelx;
    private javax.swing.JPanel verde;
    // End of variables declaration//GEN-END:variables
}
