/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;



/**
 *
 * @author astuard
 */
public class Usurios extends javax.swing.JFrame {
    int xMause,yMause;
    Login lg;
    private Object txtnuevousuario1;
    
   
    /**
     * Creates new form Usurios
     */
    public Usurios() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnuevousuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnuevopassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        negro = new javax.swing.JPanel();
        px = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 220));
        setMinimumSize(new java.awt.Dimension(280, 351));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(280, 351));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(280, 351));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 351));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtnuevousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        jLabel1.setText("Nombre de Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setText("Crear Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtnuevopassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuevopasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtnuevopassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Registro de usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 140, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Admin", "Empleado" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jToggleButton1.setText("Registrar");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, -1));

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                negroMouseDragged(evt);
            }
        });
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                negroMousePressed(evt);
            }
        });
        negro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        px.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pxMouseExited(evt);
            }
        });

        x.setBackground(new java.awt.Color(204, 204, 204));
        x.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        x.setText("   X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pxLayout = new javax.swing.GroupLayout(px);
        px.setLayout(pxLayout);
        pxLayout.setHorizontalGroup(
            pxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pxLayout.setVerticalGroup(
            pxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        negro.add(px, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 30));

        jPanel1.add(negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        btRegresar.setText("Regreser");
        btRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 80, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnuevopasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuevopasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnuevopasswordActionPerformed

    private void negroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMousePressed
        // TODO add your handling code here:
        xMause=evt.getX();
        yMause=evt.getY();
    }//GEN-LAST:event_negroMousePressed

    private void negroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMause,y-yMause);
    }//GEN-LAST:event_negroMouseDragged

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        // TODO add your handling code here:
        px.setBackground(Color.red);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        px.setBackground(Color.gray); 
    }//GEN-LAST:event_xMouseExited

    private void pxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pxMouseClicked
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_pxMouseClicked

    private void pxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pxMouseEntered
        // TODO add your handling code here:
        px.setBackground(Color.red);
    }//GEN-LAST:event_pxMouseEntered

    private void pxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pxMouseExited
        // TODO add your handling code here:
        px.setBackground(Color.gray); 
    }//GEN-LAST:event_pxMouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here                                             
    String url = "jdbc:postgresql://localhost:5432/Inventrio";
    String usuarioDB = "postgres";
    String contrasenaDB = "messi";

    String nuevoUsuario = txtnuevousuario.getText();
    String nuevaContrasena = txtnuevopassword.getText();

    try (Connection conn = DriverManager.getConnection(url, usuarioDB, contrasenaDB)) {
        String countQuery = "SELECT COUNT(*) FROM usuarios";
        int cantidadUsuarios = 0;

        try (Statement stmtCount = conn.createStatement()) {
            ResultSet rs = stmtCount.executeQuery(countQuery);
            if (rs.next()) {
                cantidadUsuarios = rs.getInt(1);
            }
        }

        if (cantidadUsuarios >= 3) {
            JOptionPane.showMessageDialog(null, "Ya existen 3 o más usuarios. No se pueden crear más.");
            return;
        }

        String rol = (cantidadUsuarios == 0) ? "admin" : "usuario";

        String insertQuery = "INSERT INTO usuarios (nombre_usuario, contrasena, rol) VALUES (?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(insertQuery)) {
            stmt.setString(1, nuevoUsuario);
            stmt.setString(2, nuevaContrasena);
            stmt.setString(3, rol);

            int filasAfectadas = stmt.executeUpdate();
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "Usuario creado con éxito. Rol: " + rol);

                // Abrir la interfaz principal después de crear el usuario
                Interfas vtn = new Interfas();
                vtn.setVisible(true);
                vtn.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(null, "Error al crear el usuario.");
            }
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }

 
        
                                      
   
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        Login vtnL=new Login();
        vtnL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRegresarActionPerformed

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked
        // TODO add your handling code here:'
        Login Loginvtn = new Login();
        Loginvtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRegresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel negro;
    private javax.swing.JPanel px;
    private javax.swing.JTextField txtnuevopassword;
    private javax.swing.JTextField txtnuevousuario;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
